# Practical 10

## Aim : Apply SVD on a matrix using numpy and TruncateSVD

...............................SVD using numpy on a matrix....................................

In [1]:
import numpy as np
from numpy.linalg import svd

In [2]:
# Define your matrix as 2-d numpy array
A = np.array([[4,0],[3,-5]])
U, S, VT = svd(A)

In [3]:
print("Left Singular Vectors:")
print(U)
print("\nSingular Values:")
print(np.diag(S))
print("\nRight Singular Vectors:")
print(VT)

Left Singular Vectors:
[[-0.4472136  -0.89442719]
 [-0.89442719  0.4472136 ]]

Singular Values:
[[6.32455532 0.        ]
 [0.         3.16227766]]

Right Singular Vectors:
[[-0.70710678  0.70710678]
 [-0.70710678 -0.70710678]]


In [4]:
# Check that this is an exact decomposition
# @ is used to directly multiply matrices
print(U @ np.diag(S) @ VT)

[[ 4.00000000e+00 -1.11022302e-15]
 [ 3.00000000e+00 -5.00000000e+00]]


In [5]:
# Practice

In [6]:
B = np.array([[3,2], [3,3], [-2,2]])
U, S, VT = svd(B)

In [7]:
print("Left Singular Vectors:")
print(U)
print("\nSingular Values:")
print(np.diag(S))
print("\nRight Singular Vectors:")
print(VT)

Left Singular Vectors:
[[-0.64749817  0.10759258  0.75443354]
 [-0.7599438  -0.16501062 -0.62869461]
 [ 0.05684667 -0.9804057   0.18860838]]

Singular Values:
[[5.54801894 0.        ]
 [0.         2.86696457]]

Right Singular Vectors:
[[-0.7815437 -0.6238505]
 [ 0.6238505 -0.7815437]]


In [8]:
# Check that this is an exact decomposition
# @ is used to directly multiply matrices
# print(U @ np.diag(S) @ VT)

In [9]:
C = ([[4,3,2], [-3,0,4]])
U, S, VT = svd(C)

In [10]:
print("Left Singular Vectors:")
print(U)
print("\nSingular Values:")
print(np.diag(S))
print("\nRight Singular Vectors:")
print(VT)

Left Singular Vectors:
[[ 0.85065081  0.52573111]
 [-0.52573111  0.85065081]]

Singular Values:
[[5.6100032  0.        ]
 [0.         4.74635271]]

Right Singular Vectors:
[[ 0.88766377  0.45489322 -0.07159048]
 [-0.09460485  0.33229586  0.93841856]
 [ 0.45066946 -0.82622734  0.33800209]]


In [11]:
# Check that this is an exact decomposition
# @ is used to directly multiply matrices
# print(U @ np.diag(S) @ VT)

...................................................SVD using TruncateSVD...........................................

In [12]:
import numpy as np
from sklearn.decomposition import TruncatedSVD
A = np.array([[-1, 2, 0],[2, 0, -2],[0, -2, 1]])
print("Orignal matrix:")
print(A)

Orignal matrix:
[[-1  2  0]
 [ 2  0 -2]
 [ 0 -2  1]]


In [13]:
svd = TruncatedSVD(n_components = 2)
A_transf = svd.fit_transform(A)
print("Transformed Matrix after reducing to 2 features:")
print(A_transf)

Transformed Matrix after reducing to 2 features:
[[ 2.2 -0.4]
 [-0.4  2.8]
 [-2.  -1. ]]


In [14]:
print("Singular values:")
print(svd.singular_values_)

Singular values:
[3. 3.]
